[package]
name = "flying_v"
version = "0.1.0"
authors = ["Elliot Jackson <elliotekj@gmail.com>"]

[dependencies]
dotenv = "0.8.0"
globset = "0.1.3"
lazy_static = "0.2.2"
pulldown-cmark = "0.0.8"
serde_json = "0.9.8"
tera = "0.7.2"
walkdir = "1.0.7"
